### ISSUE TITLE
Location list closes and doesn't reopen after clicking item

### ISSUE THREAD

**Issue by Lyude** [Valloric/ListToggle#1]
Hi. I just set up your plugin and I've noticed that whenever I click on an error in the location list after bringing it up with the ListToggle key I've assigned, the location list closes after jumping to the position of the error. Afterwards, pressing the ListToggle key doesn't bring the list back up. The only way I seem to be able to get it to reappear is by manually running `:lclose`, then striking the key again.

**Comment by d0u9** [comment]
I have the same problem with YCM

**Comment by Psi57** [comment]
Me,too

**Comment by wfxr** [comment]
I have fixed the problem by rewriting the toggle logic and created a pull request to @Valloric . You can try it from my fork before it been merged @Wuxiangdong @d0u9 @Lyude. Here is the link:
https://github.com/wfxr/ListToggle

**Comment by Psi57** [comment]
@wfxr
Thanks.

**Comment by d0u9** [comment]
Thx @wfxr

**Comment by Valloric** [comment]
That PR has been merged a while ago, so this issue is fixed.
