### ISSUE TITLE
Toggling no longer works

### ISSUE THREAD

**Issue by cspiegel** [Valloric/ListToggle#11]
Toggling of both the quickfix and location list no longer works.  The windows are opened properly, but are no longer closed.  I bisected this down to Vim [patch 8.1.0877](https://github.com/vim/vim/commit/ee8188fc74a7cf9ee7acb634b2bb7a032d0cb24c).

**Comment by andys8** [comment]
I can verify the behavior. The plugin is currently not working.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb  7 2019 13:12:21)
Included patches: 1-877
```

**Comment by Frydac** [comment]
danielwe 's fix seems to work for me, thx!

**Comment by meilke** [comment]
The proposed fix works for me as well on:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 11:47:07)
Included patches: 1-946
```
