### ISSUE TITLE
Don't use key maps

### ISSUE THREAD

**Issue by simonsmith** [Valloric/ListToggle#6]
Is there a way to prevent the plugin from mapping the keys for location and quickfix? Or perhaps changing them to something else?

Cheers

**Comment by sunaku** [comment]
See pull request #7.

**Comment by Valloric** [comment]
See my response to #7.

**Comment by teto** [comment]
It would be cool for the reasons mentioned here http://whileimautomaton.net/2008/09/27022735 to add <Plug> components. This should be backwards compatible while allowing for more customization.
```
nnoremap <silent> <Plug>(ListToggleQToggle) :QToggle<Return>
nnoremap <silent> <Plug>(ListToggleLToggle) :LToggle<Return>
```
